{{- if .Values.kafka.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-console-secrets-kafka"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: kafka
stringData:
  DEEPFENCE_KAFKA_BROKERS: "deepfence-kafka-broker.{{ .Release.Namespace }}.svc:9092"
{{- end }}
