{{- if .Values.postgresql.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-postgresql"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: postgresql
stringData:
    {{- range $k, $v := .Values.postgresql.secrets }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}