---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "deepfence-console-config"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
data:
  DEEPFENCE_DEBUG: "false"
  DEEPFENCE_SAAS_DEPLOYMENT: "false"
  UI_SERVICE_NAME: "deepfence-ui"
  UI_SERVICE_PORT: {{ .Values.ui.service.port | quote }}
  API_SERVICE_HOST: "deepfence-server"
  API_SERVICE_PORT: {{ .Values.server.service.port | quote }}
  FILE_SERVER_HOST: "deepfence-file-server"
  FILE_SERVER_PORT: "9000"