{{- if .Values.postgresql.create }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "deepfence-postgresql-{{ .Release.Name }}"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: postgresql
spec:
  storageClassName: {{ .Values.postgresql.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.volumeSize }}
{{- end }}