{{- if .Values.minio.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-file-server
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
      component: minio
  template:
    metadata:
      {{- with .Values.minio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
        component: minio
    spec:
      serviceAccountName: {{ include "deepfence-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.minio.podSecurityContext | nindent 8 }}
      containers:
        - name: minio
          securityContext:
            {{- toYaml .Values.minio.securityContext | nindent 12 }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: "deepfence-file-server"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: tcp
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
      {{- with .Values.minio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "deepfence-file-server-{{ .Release.Name }}"
---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-file-server
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: minio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: tcp
      protocol: TCP
    - name: tcp
      port: 9090
      targetPort: tcp
      protocol: TCP
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    component: minio
{{- end }}