{{- if .Values.kafka.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-kafka-broker"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: kafka-broker
stringData:
  STORAGE_UUID: {{ default "" .Values.kafka.storageUUID }}
{{- end }}