{{- if .Values.postgresql.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-console-secrets-postgresql"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: postgresql
stringData:
  DEEPFENCE_POSTGRES_USER_DB_PORT: "5432"
  DEEPFENCE_POSTGRES_USER_DB_HOST: deepfence-postgresql
  DEEPFENCE_POSTGRES_USER_DB_SSLMODE: disable
  DEEPFENCE_POSTGRES_USER_DB_USER: {{ .Values.postgresql.secrets.POSTGRES_USER | quote }}
  DEEPFENCE_POSTGRES_USER_DB_PASSWORD: {{ .Values.postgresql.secrets.POSTGRES_PASSWORD | quote }}
  DEEPFENCE_POSTGRES_USER_DB_NAME: {{ .Values.postgresql.secrets.POSTGRES_DB | quote }}
{{- end }}