name: Build & Publish images

on:
  workflow_dispatch:

env:
  DF_IMG_TAG: $GITHUB_SHA

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Build images
        run: |
          make
      -
        name: Push images
        run: |
          make publish
